"""Doc Restructure Skill - Deterministic primitives for markdown document restructuring."""

from .markdown_sections import (
    normalize_heading,
    HeadingOccurrence,
    iter_headings,
    extract_section_by_heading,
    coverage_check,
    make_safe_slug,
    extract_all_h2_section_ranges,
    normalize_url,
    body_urls,
    sources_urls,
    suggest_url_category,
    audit_links,
    add_heading_anchors,
    strip_front_matter,
    add_front_matter,
    extract_ial_headings,
    apply_anchor_map,
    find_orphaned_refs,
    make_slug,
    demote_headings,
    promote_headings,
    extract_first_h1,
    slugify_anchor,
    build_combined_document,
)

__all__ = [
    "normalize_heading",
    "HeadingOccurrence",
    "iter_headings",
    "extract_section_by_heading",
    "coverage_check",
    "make_safe_slug",
    "extract_all_h2_section_ranges",
    "normalize_url",
    "body_urls",
    "sources_urls",
    "suggest_url_category",
    "audit_links",
    "add_heading_anchors",
    "strip_front_matter",
    "add_front_matter",
    "extract_ial_headings",
    "apply_anchor_map",
    "find_orphaned_refs",
    "make_slug",
    "demote_headings",
    "promote_headings",
    "extract_first_h1",
    "slugify_anchor",
    "build_combined_document",
]
